-- migrations/add_therapist_notification_enum_values.sql
--
-- ✅ VAHAOLANA TENA IZY (root cause) ho an'ny error:
--    psycopg2.errors.InvalidTextRepresentation: valeur en entrée
--    invalide pour le enum notification_type : « therapist_approved »
--
-- Ny ENUM PostgreSQL "notification_type" dia mbola tsy nisy ireto
-- valeur roa ireto, izay ampiasain'ny app.api.admin (approve/reject
-- therapist). Ampio izy ireo mba tena handeha ny notification (fa tsy
-- ho "avalées" fotsiny amin'ny try/except ao amin'ny admin.py).
--
-- ⚠️ PostgreSQL: "ALTER TYPE ... ADD VALUE" dia TSY azo atao anaty
-- transaction miaraka amin'ny fampiasana io valeur vaovao io (na
-- amin'ny statement iray ihany) raha PostgreSQL < 12. Atao statement
-- tokana isaky ny ADD VALUE, ary tsy asiana COMMIT/ROLLBACK
-- manaraka azy avy hatrany.
--
-- Ampiasao amin'ny psql na amin'ny outil GUI (pgAdmin, DBeaver, ...):

ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'therapist_approved';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'therapist_rejected';

-- ✅ Raha mampiasa Alembic ianao ho an'ny migrations, ampidiro toy
-- izao ao anaty fichier migration vaovao (`alembic revision -m
-- "add therapist notification enum values"`):
--
--   def upgrade():
--       op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'therapist_approved'")
--       op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'therapist_rejected'")
--
--   def downgrade():
--       # PostgreSQL tsy mamela famafana valeur amin'ny ENUM mora
--       # foana — tsy misy downgrade tsotra ho an'ity.
--       pass
--
-- 💡 Raha mety hisy valeur hafa tsy mbola ao amin'ny ENUM ihany koa
-- (ohatra: notification hafa ampiasain'ny app amin'ny toerana hafa),
-- ampiharo ny fomba fitadiavana manaraka mba hahitana azy rehetra:
--
--   SELECT unnest(enum_range(NULL::notification_type))::text AS existing_values;
--
-- Ampitahao amin'ny valeur rehetra tadiavin'ny code Python (grep
-- "send_notification(" any amin'ny app/), dia ampio izay tsy mbola
-- ao araka ny modely eo ambony.
