"""fix_earnings_relationships

Revision ID: 2171f07c3f13
Revises: 3a80a0aebbdb
Create Date: 2026-07-06 17:44:11.869576

"""

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# Revision identifiers, used by Alembic.
revision = "2171f07c3f13"
down_revision = "3a80a0aebbdb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
