"""initial_migration_clean

Revision ID: 3a80a0aebbdb
Revises: 586a92d6f71e
Create Date: 2026-07-06 17:33:15.164540

"""

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# Revision identifiers, used by Alembic.
revision = "3a80a0aebbdb"
down_revision = "586a92d6f71e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
