"""initial_migration_clean

Revision ID: 586a92d6f71e
Revises: 684f4c994266
Create Date: 2026-07-06 17:23:39.501971

"""

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# Revision identifiers, used by Alembic.
revision = "586a92d6f71e"
down_revision = "684f4c994266"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
