"""initial_migration_clean

Revision ID: 684f4c994266
Revises: aa756b7acf6d
Create Date: 2026-07-06 16:15:59.853236

"""

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# Revision identifiers, used by Alembic.
revision = "684f4c994266"
down_revision = "aa756b7acf6d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
