"""initial_migration_clean

Revision ID: 6e57c65c8e0e
Revises: 2ec850a3bc2e
Create Date: 2026-07-06 18:15:20.374864

"""

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# Revision identifiers, used by Alembic.
revision = "6e57c65c8e0e"
down_revision = "2ec850a3bc2e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
