"""initial_migration_clean

Revision ID: aa756b7acf6d
Revises:
Create Date: 2026-07-06 15:25:17.994168

"""

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# Revision identifiers, used by Alembic.
revision = "aa756b7acf6d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("model_type", sa.String(length=50), nullable=False),
        sa.Column("accuracy", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("precision", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("recall", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("f1_score", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("model_path", sa.String(length=255), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_production", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("trained_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deployed_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("idx_ai_models_is_active", "ai_models", ["is_active"], unique=False)
    op.create_index(
        "idx_ai_models_model_type", "ai_models", ["model_type"], unique=False
    )
    op.create_index(op.f("ix_ai_models_id"), "ai_models", ["id"], unique=False)
    op.create_table(
        "massage_addons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_massage_addons_id"), "massage_addons", ["id"], unique=False
    )
    op.create_table(
        "massage_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon_url", sa.String(length=255), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_massage_categories_id"), "massage_categories", ["id"], unique=False
    )
    op.create_table(
        "massage_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("duration_min", sa.Integer(), nullable=True),
        sa.Column("duration_max", sa.Integer(), nullable=True),
        sa.Column("min_price", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column(
            "recommended_price", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            "category",
            sa.Enum(
                "relaxant",
                "therapeutique",
                "sportif",
                "reflexologie",
                "prenatal",
                "personnalise",
                name="massage_category",
            ),
            nullable=True,
        ),
        sa.Column("icon_url", sa.String(length=255), nullable=True),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_massage_types_id"), "massage_types", ["id"], unique=False)
    op.create_table(
        "platform_analytics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.TIMESTAMP(), nullable=False),
        sa.Column("total_users", sa.Integer(), nullable=True),
        sa.Column("new_users", sa.Integer(), nullable=True),
        sa.Column("active_users", sa.Integer(), nullable=True),
        sa.Column("total_therapists", sa.Integer(), nullable=True),
        sa.Column("active_therapists", sa.Integer(), nullable=True),
        sa.Column("online_therapists", sa.Integer(), nullable=True),
        sa.Column("total_bookings", sa.Integer(), nullable=True),
        sa.Column("completed_bookings", sa.Integer(), nullable=True),
        sa.Column("cancelled_bookings", sa.Integer(), nullable=True),
        sa.Column("total_revenue", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("total_commission", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("net_revenue", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("total_payments", sa.Integer(), nullable=True),
        sa.Column("payment_amount", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("total_reviews", sa.Integer(), nullable=True),
        sa.Column("average_rating", sa.DECIMAL(precision=3, scale=2), nullable=True),
        sa.Column("sos_alerts", sa.Integer(), nullable=True),
        sa.Column("resolved_sos", sa.Integer(), nullable=True),
        sa.Column(
            "predicted_revenue", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column("growth_rate", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("churn_rate", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_platform_analytics_date"), "platform_analytics", ["date"], unique=True
    )
    op.create_index(
        op.f("ix_platform_analytics_id"), "platform_analytics", ["id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fullname", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("CLIENT", "THERAPIST", "ADMIN", name="user_role"),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("profile_image", sa.String(length=255), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("experience_years", sa.Integer(), nullable=True),
        sa.Column("rating", sa.DECIMAL(precision=3, scale=2), nullable=True),
        sa.Column("total_reviews", sa.Integer(), nullable=True),
        sa.Column("is_online", sa.Boolean(), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=True),
        sa.Column("service_radius", sa.Integer(), nullable=True),
        sa.Column("base_price", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum("pending", "approved", "rejected", name="verification_status"),
            nullable=True,
        ),
        sa.Column("identity_document_url", sa.String(length=255), nullable=True),
        sa.Column("certificate_url", sa.String(length=255), nullable=True),
        sa.Column("commission_rate", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("subscription_type", sa.String(length=20), nullable=True),
        sa.Column("subscription_end_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("otp_code", sa.String(length=6), nullable=True),
        sa.Column("otp_expires_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("latitude", sa.DECIMAL(precision=10, scale=8), nullable=True),
        sa.Column("longitude", sa.DECIMAL(precision=11, scale=8), nullable=True),
        sa.Column("last_location", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_users_email", "users", ["email"], unique=False)
    op.create_index("idx_users_is_active", "users", ["is_active"], unique=False)
    op.create_index("idx_users_phone", "users", ["phone"], unique=False)
    op.create_index("idx_users_role", "users", ["role"], unique=False)
    op.create_index(
        "idx_users_verification_status", "users", ["verification_status"], unique=False
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)
    op.create_table(
        "blocked_dates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("therapist_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.TIMESTAMP(), nullable=False),
        sa.Column("end_date", sa.TIMESTAMP(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("is_all_day", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_blocked_dates_end_date", "blocked_dates", ["end_date"], unique=False
    )
    op.create_index(
        "idx_blocked_dates_start_date", "blocked_dates", ["start_date"], unique=False
    )
    op.create_index(
        "idx_blocked_dates_therapist_id",
        "blocked_dates",
        ["therapist_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_blocked_dates_end_date"), "blocked_dates", ["end_date"], unique=False
    )
    op.create_index(op.f("ix_blocked_dates_id"), "blocked_dates", ["id"], unique=False)
    op.create_index(
        op.f("ix_blocked_dates_start_date"),
        "blocked_dates",
        ["start_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_blocked_dates_therapist_id"),
        "blocked_dates",
        ["therapist_id"],
        unique=False,
    )
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("therapist_id", sa.Integer(), nullable=True),
        sa.Column("massage_type_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "negotiating",
                "confirmed",
                "in_progress",
                "completed",
                "cancelled_by_client",
                "cancelled_by_therapist",
                "expired",
                name="booking_status",
            ),
            nullable=True,
        ),
        sa.Column(
            "client_price_proposed", sa.DECIMAL(precision=10, scale=2), nullable=False
        ),
        sa.Column(
            "therapist_initial_price", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column("final_price", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("client_latitude", sa.DECIMAL(precision=10, scale=8), nullable=True),
        sa.Column("client_longitude", sa.DECIMAL(precision=11, scale=8), nullable=True),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("client_location", sa.String(length=255), nullable=True),
        sa.Column("scheduled_date", sa.TIMESTAMP(), nullable=False),
        sa.Column("scheduled_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("actual_start_time", sa.TIMESTAMP(), nullable=True),
        sa.Column("actual_end_time", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "preferred_gender",
            sa.Enum("male", "female", "any", name="gender_preference"),
            nullable=True,
        ),
        sa.Column("special_instructions", sa.Text(), nullable=True),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("expires_at", sa.TIMESTAMP(), nullable=True),
        sa.CheckConstraint("client_price_proposed >= 0", name="check_price_positive"),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["massage_type_id"],
            ["massage_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_bookings_client_id", "bookings", ["client_id"], unique=False)
    op.create_index("idx_bookings_expires_at", "bookings", ["expires_at"], unique=False)
    op.create_index(
        "idx_bookings_scheduled_date", "bookings", ["scheduled_date"], unique=False
    )
    op.create_index("idx_bookings_status", "bookings", ["status"], unique=False)
    op.create_index(
        "idx_bookings_therapist_id", "bookings", ["therapist_id"], unique=False
    )
    op.create_index(
        op.f("ix_bookings_client_id"), "bookings", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_bookings_created_at"), "bookings", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_bookings_expires_at"), "bookings", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_bookings_id"), "bookings", ["id"], unique=False)
    op.create_index(
        op.f("ix_bookings_scheduled_date"), "bookings", ["scheduled_date"], unique=False
    )
    op.create_index(op.f("ix_bookings_status"), "bookings", ["status"], unique=False)
    op.create_index(
        op.f("ix_bookings_therapist_id"), "bookings", ["therapist_id"], unique=False
    )
    op.create_table(
        "emergency_contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("relation", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_emergency_contacts_user_id",
        "emergency_contacts",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emergency_contacts_id"), "emergency_contacts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_emergency_contacts_user_id"),
        "emergency_contacts",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("push_enabled", sa.Boolean(), nullable=True),
        sa.Column("email_enabled", sa.Boolean(), nullable=True),
        sa.Column("sms_enabled", sa.Boolean(), nullable=True),
        sa.Column("booking_notifications", sa.Boolean(), nullable=True),
        sa.Column("offer_notifications", sa.Boolean(), nullable=True),
        sa.Column("payment_notifications", sa.Boolean(), nullable=True),
        sa.Column("review_notifications", sa.Boolean(), nullable=True),
        sa.Column("sos_notifications", sa.Boolean(), nullable=True),
        sa.Column("promotion_notifications", sa.Boolean(), nullable=True),
        sa.Column("chat_notifications", sa.Boolean(), nullable=True),
        sa.Column("silent_mode_start", sa.String(length=5), nullable=True),
        sa.Column("silent_mode_end", sa.String(length=5), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_notification_preferences_user_id",
        "notification_preferences",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_preferences_id"),
        "notification_preferences",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_preferences_user_id"),
        "notification_preferences",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "therapist_availability",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("therapist_id", sa.Integer(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=True),
        sa.Column("is_recurring", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "therapist_id",
            "day_of_week",
            "start_time",
            "end_time",
            name="unique_availability_slot",
        ),
    )
    op.create_index(
        "idx_therapist_availability_day_of_week",
        "therapist_availability",
        ["day_of_week"],
        unique=False,
    )
    op.create_index(
        "idx_therapist_availability_therapist_id",
        "therapist_availability",
        ["therapist_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_therapist_availability_id"),
        "therapist_availability",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_therapist_availability_therapist_id"),
        "therapist_availability",
        ["therapist_id"],
        unique=False,
    )
    op.create_table(
        "therapist_earnings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("therapist_id", sa.Integer(), nullable=False),
        sa.Column("total_earnings", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("pending_earnings", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column(
            "available_earnings", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column("total_commission", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column(
            "pending_commission", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column("total_bookings", sa.Integer(), nullable=True),
        sa.Column("completed_bookings", sa.Integer(), nullable=True),
        sa.Column("cancelled_bookings", sa.Integer(), nullable=True),
        sa.Column("today_earnings", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("week_earnings", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("month_earnings", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("year_earnings", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_therapist_earnings_id"), "therapist_earnings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_therapist_earnings_therapist_id"),
        "therapist_earnings",
        ["therapist_id"],
        unique=False,
    )
    op.create_table(
        "therapist_ratings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("therapist_id", sa.Integer(), nullable=False),
        sa.Column("average_rating", sa.DECIMAL(precision=3, scale=2), nullable=True),
        sa.Column("total_reviews", sa.Integer(), nullable=True),
        sa.Column("rating_1_count", sa.Integer(), nullable=True),
        sa.Column("rating_2_count", sa.Integer(), nullable=True),
        sa.Column("rating_3_count", sa.Integer(), nullable=True),
        sa.Column("rating_4_count", sa.Integer(), nullable=True),
        sa.Column("rating_5_count", sa.Integer(), nullable=True),
        sa.Column("last_month_rating", sa.DECIMAL(precision=3, scale=2), nullable=True),
        sa.Column("last_month_reviews", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_therapist_ratings_id"), "therapist_ratings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_therapist_ratings_therapist_id"),
        "therapist_ratings",
        ["therapist_id"],
        unique=True,
    )
    op.create_table(
        "therapist_specialties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("therapist_id", sa.Integer(), nullable=False),
        sa.Column("massage_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["massage_type_id"],
            ["massage_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_therapist_specialties_massage_type_id",
        "therapist_specialties",
        ["massage_type_id"],
        unique=False,
    )
    op.create_index(
        "idx_therapist_specialties_therapist_id",
        "therapist_specialties",
        ["therapist_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_therapist_specialties_id"),
        "therapist_specialties",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_therapist_specialties_massage_type_id"),
        "therapist_specialties",
        ["massage_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_therapist_specialties_therapist_id"),
        "therapist_specialties",
        ["therapist_id"],
        unique=False,
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "deposit",
                "withdrawal",
                "payment",
                "refund",
                "commission",
                "bonus",
                name="transaction_type",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("balance_after", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.Column("reference_type", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_transactions_created_at", "transactions", ["created_at"], unique=False
    )
    op.create_index("idx_transactions_type", "transactions", ["type"], unique=False)
    op.create_index(
        "idx_transactions_user_id", "transactions", ["user_id"], unique=False
    )
    op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
    op.create_index(
        op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False
    )
    op.create_table(
        "user_analytics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("total_bookings", sa.Integer(), nullable=True),
        sa.Column("total_spent", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("total_earnings", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("favorite_massage_types", sa.JSON(), nullable=True),
        sa.Column(
            "average_rating_given", sa.DECIMAL(precision=3, scale=2), nullable=True
        ),
        sa.Column(
            "average_rating_received", sa.DECIMAL(precision=3, scale=2), nullable=True
        ),
        sa.Column("preferred_price_range", sa.JSON(), nullable=True),
        sa.Column("preferred_gender", sa.String(length=10), nullable=True),
        sa.Column("preferred_distance", sa.Integer(), nullable=True),
        sa.Column("preferred_time_slots", sa.JSON(), nullable=True),
        sa.Column("user_segment", sa.String(length=50), nullable=True),
        sa.Column("engagement_score", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("churn_risk", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("embedding_vector", sa.JSON(), nullable=True),
        sa.Column("last_active", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_user_analytics_user_id", "user_analytics", ["user_id"], unique=False
    )
    op.create_index(
        "idx_user_analytics_user_segment",
        "user_analytics",
        ["user_segment"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_analytics_id"), "user_analytics", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_user_analytics_user_id"), "user_analytics", ["user_id"], unique=True
    )
    op.create_table(
        "withdrawals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("therapist_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("fee", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("net_amount", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "completed",
                "failed",
                "cancelled",
                name="withdrawal_status",
            ),
            nullable=True,
        ),
        sa.Column(
            "method",
            sa.Enum("bank_transfer", "mobile_money", "cash", name="withdrawal_method"),
            nullable=False,
        ),
        sa.Column("bank_name", sa.String(length=100), nullable=True),
        sa.Column("account_number", sa.String(length=50), nullable=True),
        sa.Column("account_holder", sa.String(length=100), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("processed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("completed_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reference"),
    )
    op.create_index("idx_withdrawals_status", "withdrawals", ["status"], unique=False)
    op.create_index(
        "idx_withdrawals_therapist_id", "withdrawals", ["therapist_id"], unique=False
    )
    op.create_index(op.f("ix_withdrawals_id"), "withdrawals", ["id"], unique=False)
    op.create_index(
        op.f("ix_withdrawals_therapist_id"),
        "withdrawals",
        ["therapist_id"],
        unique=False,
    )
    op.create_table(
        "ai_predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("prediction_type", sa.String(length=50), nullable=False),
        sa.Column("predicted_price", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column(
            "recommended_price", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            "acceptance_probability", sa.DECIMAL(precision=5, scale=2), nullable=True
        ),
        sa.Column("confidence_score", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("recommended_therapist_id", sa.Integer(), nullable=True),
        sa.Column("recommended_massage_type_id", sa.Integer(), nullable=True),
        sa.Column("factors", sa.JSON(), nullable=True),
        sa.Column("features", sa.JSON(), nullable=True),
        sa.Column("model_version", sa.String(length=50), nullable=True),
        sa.Column("model_used", sa.String(length=50), nullable=True),
        sa.Column("actual_value", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("error", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("is_validated", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("validated_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recommended_massage_type_id"],
            ["massage_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recommended_therapist_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_ai_predictions_booking_id", "ai_predictions", ["booking_id"], unique=False
    )
    op.create_index(
        "idx_ai_predictions_created_at", "ai_predictions", ["created_at"], unique=False
    )
    op.create_index(
        "idx_ai_predictions_prediction_type",
        "ai_predictions",
        ["prediction_type"],
        unique=False,
    )
    op.create_index(
        "idx_ai_predictions_user_id", "ai_predictions", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_predictions_booking_id"),
        "ai_predictions",
        ["booking_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_predictions_id"), "ai_predictions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_predictions_prediction_type"),
        "ai_predictions",
        ["prediction_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_predictions_user_id"), "ai_predictions", ["user_id"], unique=False
    )
    op.create_table(
        "booking_addons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("addon_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["addon_id"],
            ["massage_addons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_booking_addons_id"), "booking_addons", ["id"], unique=False
    )
    op.create_table(
        "booking_analytics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("response_time_seconds", sa.Integer(), nullable=True),
        sa.Column("confirmation_time_seconds", sa.Integer(), nullable=True),
        sa.Column("completion_time_seconds", sa.Integer(), nullable=True),
        sa.Column("client_satisfaction", sa.Integer(), nullable=True),
        sa.Column("therapist_satisfaction", sa.Integer(), nullable=True),
        sa.Column("revenue", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("commission", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("net_revenue", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_booking_analytics_booking_id"),
        "booking_analytics",
        ["booking_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_booking_analytics_id"), "booking_analytics", ["id"], unique=False
    )
    op.create_table(
        "booking_slots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("therapist_id", sa.Integer(), nullable=False),
        sa.Column("slot_date", sa.TIMESTAMP(), nullable=False),
        sa.Column("slot_duration", sa.Integer(), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=True),
        sa.Column("is_booked", sa.Boolean(), nullable=True),
        sa.Column("booking_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("therapist_id", "slot_date", name="unique_slot"),
    )
    op.create_index(
        "idx_booking_slots_is_available",
        "booking_slots",
        ["is_available"],
        unique=False,
    )
    op.create_index(
        "idx_booking_slots_is_booked", "booking_slots", ["is_booked"], unique=False
    )
    op.create_index(
        "idx_booking_slots_slot_date", "booking_slots", ["slot_date"], unique=False
    )
    op.create_index(
        "idx_booking_slots_therapist_id",
        "booking_slots",
        ["therapist_id"],
        unique=False,
    )
    op.create_index(op.f("ix_booking_slots_id"), "booking_slots", ["id"], unique=False)
    op.create_index(
        op.f("ix_booking_slots_slot_date"), "booking_slots", ["slot_date"], unique=False
    )
    op.create_index(
        op.f("ix_booking_slots_therapist_id"),
        "booking_slots",
        ["therapist_id"],
        unique=False,
    )
    op.create_table(
        "massage_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("actual_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("therapist_notes", sa.Text(), nullable=True),
        sa.Column("client_feedback", sa.Text(), nullable=True),
        sa.Column("client_satisfaction", sa.Integer(), nullable=True),
        sa.Column("therapist_satisfaction", sa.Integer(), nullable=True),
        sa.Column("pressure_level", sa.String(length=20), nullable=True),
        sa.Column("client_relaxation", sa.Integer(), nullable=True),
        sa.Column("client_pain_relief", sa.Integer(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("completed_at", sa.TIMESTAMP(), nullable=True),
        sa.CheckConstraint(
            "client_satisfaction BETWEEN 1 AND 5 OR client_satisfaction IS NULL",
            name="check_client_satisfaction",
        ),
        sa.CheckConstraint(
            "therapist_satisfaction BETWEEN 1 AND 5 OR therapist_satisfaction IS NULL",
            name="check_therapist_satisfaction",
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_massage_sessions_booking_id",
        "massage_sessions",
        ["booking_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_massage_sessions_booking_id"),
        "massage_sessions",
        ["booking_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_massage_sessions_id"), "massage_sessions", ["id"], unique=False
    )
    op.create_table(
        "negotiations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "user_type",
            sa.Enum("client", "therapist", name="user_type_enum"),
            nullable=False,
        ),
        sa.Column("price_offered", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "sent", "accepted", "rejected", "expired", name="negotiation_status"
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("expires_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_negotiations_booking_id", "negotiations", ["booking_id"], unique=False
    )
    op.create_index("idx_negotiations_status", "negotiations", ["status"], unique=False)
    op.create_index(
        "idx_negotiations_user_id", "negotiations", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_negotiations_booking_id"), "negotiations", ["booking_id"], unique=False
    )
    op.create_index(
        op.f("ix_negotiations_expires_at"), "negotiations", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_negotiations_id"), "negotiations", ["id"], unique=False)
    op.create_index(
        op.f("ix_negotiations_status"), "negotiations", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_negotiations_user_id"), "negotiations", ["user_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "booking",
                "offer",
                "payment",
                "review",
                "sos",
                "system",
                "promotion",
                "reminder",
                "chat",
                "therapist",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("is_delivered", sa.Boolean(), nullable=True),
        sa.Column("is_sent", sa.Boolean(), nullable=True),
        sa.Column(
            "priority",
            sa.Enum("low", "normal", "high", "urgent", name="notification_priority"),
            nullable=True,
        ),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("read_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("delivered_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("sent_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_notifications_created_at", "notifications", ["created_at"], unique=False
    )
    op.create_index(
        "idx_notifications_is_read", "notifications", ["is_read"], unique=False
    )
    op.create_index("idx_notifications_type", "notifications", ["type"], unique=False)
    op.create_index(
        "idx_notifications_user_id", "notifications", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_booking_id"),
        "notifications",
        ["booking_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.create_index(
        op.f("ix_notifications_is_read"), "notifications", ["is_read"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_type"), "notifications", ["type"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.create_table(
        "offers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("therapist_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("counter_price", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "accepted",
                "rejected",
                "countered",
                "expired",
                name="offer_status",
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("expires_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("responded_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_offers_booking_id", "offers", ["booking_id"], unique=False)
    op.create_index("idx_offers_status", "offers", ["status"], unique=False)
    op.create_index("idx_offers_therapist_id", "offers", ["therapist_id"], unique=False)
    op.create_index(
        op.f("ix_offers_booking_id"), "offers", ["booking_id"], unique=False
    )
    op.create_index(op.f("ix_offers_id"), "offers", ["id"], unique=False)
    op.create_index(op.f("ix_offers_status"), "offers", ["status"], unique=False)
    op.create_index(
        op.f("ix_offers_therapist_id"), "offers", ["therapist_id"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column(
            "method",
            sa.Enum(
                "mobile_money", "card", "cash", "vanila_pay", name="payment_method"
            ),
            nullable=False,
        ),
        sa.Column(
            "provider",
            sa.Enum(
                "mvola",
                "orange_money",
                "airtel_money",
                "stripe",
                "vanila_pay",
                name="payment_provider",
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "completed",
                "failed",
                "refunded",
                "cancelled",
                name="payment_status",
            ),
            nullable=True,
        ),
        sa.Column("transaction_id", sa.String(length=100), nullable=True),
        sa.Column("payment_intent_id", sa.String(length=100), nullable=True),
        sa.Column("payment_data", sa.JSON(), nullable=True),
        sa.Column("payment_metadata", sa.JSON(), nullable=True),
        sa.Column("payer_name", sa.String(length=100), nullable=True),
        sa.Column("payer_phone", sa.String(length=20), nullable=True),
        sa.Column("payer_email", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("completed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("refunded_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_payments_booking_id", "payments", ["booking_id"], unique=False)
    op.create_index("idx_payments_status", "payments", ["status"], unique=False)
    op.create_index(
        "idx_payments_transaction_id", "payments", ["transaction_id"], unique=False
    )
    op.create_index("idx_payments_user_id", "payments", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_payments_booking_id"), "payments", ["booking_id"], unique=False
    )
    op.create_index(
        op.f("ix_payments_created_at"), "payments", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_payments_id"), "payments", ["id"], unique=False)
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_index(
        op.f("ix_payments_transaction_id"), "payments", ["transaction_id"], unique=True
    )
    op.create_index(op.f("ix_payments_user_id"), "payments", ["user_id"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("reviewer_id", sa.Integer(), nullable=False),
        sa.Column("therapist_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("response_from_therapist", sa.Text(), nullable=True),
        sa.Column("is_anonymous", sa.Boolean(), nullable=True),
        sa.Column("professionalism", sa.Integer(), nullable=True),
        sa.Column("quality", sa.Integer(), nullable=True),
        sa.Column("punctuality", sa.Integer(), nullable=True),
        sa.Column("cleanliness", sa.Integer(), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("is_flagged", sa.Boolean(), nullable=True),
        sa.Column("flag_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("therapist_responded_at", sa.TIMESTAMP(), nullable=True),
        sa.CheckConstraint(
            "cleanliness BETWEEN 1 AND 5 OR cleanliness IS NULL",
            name="check_cleanliness",
        ),
        sa.CheckConstraint(
            "professionalism BETWEEN 1 AND 5 OR professionalism IS NULL",
            name="check_professionalism",
        ),
        sa.CheckConstraint(
            "punctuality BETWEEN 1 AND 5 OR punctuality IS NULL",
            name="check_punctuality",
        ),
        sa.CheckConstraint(
            "quality BETWEEN 1 AND 5 OR quality IS NULL", name="check_quality"
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name="check_rating_range"),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_reviews_booking_id", "reviews", ["booking_id"], unique=False)
    op.create_index("idx_reviews_rating", "reviews", ["rating"], unique=False)
    op.create_index("idx_reviews_reviewer_id", "reviews", ["reviewer_id"], unique=False)
    op.create_index(
        "idx_reviews_therapist_id", "reviews", ["therapist_id"], unique=False
    )
    op.create_index(
        op.f("ix_reviews_booking_id"), "reviews", ["booking_id"], unique=True
    )
    op.create_index(op.f("ix_reviews_id"), "reviews", ["id"], unique=False)
    op.create_index(
        op.f("ix_reviews_reviewer_id"), "reviews", ["reviewer_id"], unique=False
    )
    op.create_index(
        op.f("ix_reviews_therapist_id"), "reviews", ["therapist_id"], unique=False
    )
    op.create_table(
        "safety_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column(
            "check_type",
            sa.Enum(
                "client_checkin",
                "therapist_checkin",
                "mid_session",
                "post_session",
                name="safety_check_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "ok", "warning", "emergency", name="safety_check_status"
            ),
            nullable=True,
        ),
        sa.Column("latitude", sa.DECIMAL(precision=10, scale=8), nullable=True),
        sa.Column("longitude", sa.DECIMAL(precision=11, scale=8), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("checked_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("expires_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_safety_checks_booking_id", "safety_checks", ["booking_id"], unique=False
    )
    op.create_index(
        "idx_safety_checks_status", "safety_checks", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_safety_checks_booking_id"),
        "safety_checks",
        ["booking_id"],
        unique=False,
    )
    op.create_index(op.f("ix_safety_checks_id"), "safety_checks", ["id"], unique=False)
    op.create_table(
        "sos_alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=True),
        sa.Column(
            "alert_type",
            sa.Enum(
                "client", "therapist", "other", "emergency", name="alert_type_enum"
            ),
            nullable=False,
        ),
        sa.Column("latitude", sa.DECIMAL(precision=10, scale=8), nullable=True),
        sa.Column("longitude", sa.DECIMAL(precision=11, scale=8), nullable=True),
        sa.Column("alert_location", sa.String(length=255), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "resolved", "cancelled", name="sos_status"),
            nullable=True,
        ),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum("low", "medium", "high", "critical", name="sos_severity"),
            nullable=True,
        ),
        sa.Column("responded_by", sa.Integer(), nullable=True),
        sa.Column("response_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("resolved_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("cancelled_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["responded_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_sos_alerts_booking_id", "sos_alerts", ["booking_id"], unique=False
    )
    op.create_index("idx_sos_alerts_status", "sos_alerts", ["status"], unique=False)
    op.create_index("idx_sos_alerts_user_id", "sos_alerts", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_sos_alerts_booking_id"), "sos_alerts", ["booking_id"], unique=False
    )
    op.create_index(
        op.f("ix_sos_alerts_created_at"), "sos_alerts", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_sos_alerts_id"), "sos_alerts", ["id"], unique=False)
    op.create_index(
        op.f("ix_sos_alerts_status"), "sos_alerts", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_sos_alerts_user_id"), "sos_alerts", ["user_id"], unique=False
    )
    op.create_table(
        "ai_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prediction_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("is_helpful", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["ai_predictions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_ai_feedback_prediction_id", "ai_feedback", ["prediction_id"], unique=False
    )
    op.create_index("idx_ai_feedback_user_id", "ai_feedback", ["user_id"], unique=False)
    op.create_index(op.f("ix_ai_feedback_id"), "ai_feedback", ["id"], unique=False)
    op.create_index(
        op.f("ix_ai_feedback_prediction_id"),
        "ai_feedback",
        ["prediction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_feedback_user_id"), "ai_feedback", ["user_id"], unique=False
    )
    op.create_table(
        "refunds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payment_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("fee", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("net_amount", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "processing", "completed", "failed", name="refund_status"
            ),
            nullable=True,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("refund_id", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("processed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("completed_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("refund_id"),
    )
    op.create_index("idx_refunds_payment_id", "refunds", ["payment_id"], unique=False)
    op.create_index("idx_refunds_status", "refunds", ["status"], unique=False)
    op.create_index(op.f("ix_refunds_id"), "refunds", ["id"], unique=False)
    op.create_index(
        op.f("ix_refunds_payment_id"), "refunds", ["payment_id"], unique=False
    )
    op.create_table(
        "review_helpful",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_helpful", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_review_helpful_review_id", "review_helpful", ["review_id"], unique=False
    )
    op.create_index(
        "idx_review_helpful_user_id", "review_helpful", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_review_helpful_id"), "review_helpful", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_review_helpful_review_id"),
        "review_helpful",
        ["review_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_helpful_user_id"), "review_helpful", ["user_id"], unique=False
    )
    op.create_table(
        "review_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("reporter_id", sa.Integer(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "inappropriate",
                "fake",
                "offensive",
                "spam",
                "other",
                name="report_reason",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "reviewed", "dismissed", "action_taken", name="report_status"
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("reviewed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("admin_notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_review_reports_review_id", "review_reports", ["review_id"], unique=False
    )
    op.create_index(
        "idx_review_reports_status", "review_reports", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_review_reports_id"), "review_reports", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_review_reports_reporter_id"),
        "review_reports",
        ["reporter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_reports_review_id"),
        "review_reports",
        ["review_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_reports_review_id"), table_name="review_reports")
    op.drop_index(op.f("ix_review_reports_reporter_id"), table_name="review_reports")
    op.drop_index(op.f("ix_review_reports_id"), table_name="review_reports")
    op.drop_index("idx_review_reports_status", table_name="review_reports")
    op.drop_index("idx_review_reports_review_id", table_name="review_reports")
    op.drop_table("review_reports")
    op.drop_index(op.f("ix_review_helpful_user_id"), table_name="review_helpful")
    op.drop_index(op.f("ix_review_helpful_review_id"), table_name="review_helpful")
    op.drop_index(op.f("ix_review_helpful_id"), table_name="review_helpful")
    op.drop_index("idx_review_helpful_user_id", table_name="review_helpful")
    op.drop_index("idx_review_helpful_review_id", table_name="review_helpful")
    op.drop_table("review_helpful")
    op.drop_index(op.f("ix_refunds_payment_id"), table_name="refunds")
    op.drop_index(op.f("ix_refunds_id"), table_name="refunds")
    op.drop_index("idx_refunds_status", table_name="refunds")
    op.drop_index("idx_refunds_payment_id", table_name="refunds")
    op.drop_table("refunds")
    op.drop_index(op.f("ix_ai_feedback_user_id"), table_name="ai_feedback")
    op.drop_index(op.f("ix_ai_feedback_prediction_id"), table_name="ai_feedback")
    op.drop_index(op.f("ix_ai_feedback_id"), table_name="ai_feedback")
    op.drop_index("idx_ai_feedback_user_id", table_name="ai_feedback")
    op.drop_index("idx_ai_feedback_prediction_id", table_name="ai_feedback")
    op.drop_table("ai_feedback")
    op.drop_index(op.f("ix_sos_alerts_user_id"), table_name="sos_alerts")
    op.drop_index(op.f("ix_sos_alerts_status"), table_name="sos_alerts")
    op.drop_index(op.f("ix_sos_alerts_id"), table_name="sos_alerts")
    op.drop_index(op.f("ix_sos_alerts_created_at"), table_name="sos_alerts")
    op.drop_index(op.f("ix_sos_alerts_booking_id"), table_name="sos_alerts")
    op.drop_index("idx_sos_alerts_user_id", table_name="sos_alerts")
    op.drop_index("idx_sos_alerts_status", table_name="sos_alerts")
    op.drop_index("idx_sos_alerts_booking_id", table_name="sos_alerts")
    op.drop_table("sos_alerts")
    op.drop_index(op.f("ix_safety_checks_id"), table_name="safety_checks")
    op.drop_index(op.f("ix_safety_checks_booking_id"), table_name="safety_checks")
    op.drop_index("idx_safety_checks_status", table_name="safety_checks")
    op.drop_index("idx_safety_checks_booking_id", table_name="safety_checks")
    op.drop_table("safety_checks")
    op.drop_index(op.f("ix_reviews_therapist_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_reviewer_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_booking_id"), table_name="reviews")
    op.drop_index("idx_reviews_therapist_id", table_name="reviews")
    op.drop_index("idx_reviews_reviewer_id", table_name="reviews")
    op.drop_index("idx_reviews_rating", table_name="reviews")
    op.drop_index("idx_reviews_booking_id", table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_payments_user_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_transaction_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_created_at"), table_name="payments")
    op.drop_index(op.f("ix_payments_booking_id"), table_name="payments")
    op.drop_index("idx_payments_user_id", table_name="payments")
    op.drop_index("idx_payments_transaction_id", table_name="payments")
    op.drop_index("idx_payments_status", table_name="payments")
    op.drop_index("idx_payments_booking_id", table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_offers_therapist_id"), table_name="offers")
    op.drop_index(op.f("ix_offers_status"), table_name="offers")
    op.drop_index(op.f("ix_offers_id"), table_name="offers")
    op.drop_index(op.f("ix_offers_booking_id"), table_name="offers")
    op.drop_index("idx_offers_therapist_id", table_name="offers")
    op.drop_index("idx_offers_status", table_name="offers")
    op.drop_index("idx_offers_booking_id", table_name="offers")
    op.drop_table("offers")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_type"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_is_read"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_booking_id"), table_name="notifications")
    op.drop_index("idx_notifications_user_id", table_name="notifications")
    op.drop_index("idx_notifications_type", table_name="notifications")
    op.drop_index("idx_notifications_is_read", table_name="notifications")
    op.drop_index("idx_notifications_created_at", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_negotiations_user_id"), table_name="negotiations")
    op.drop_index(op.f("ix_negotiations_status"), table_name="negotiations")
    op.drop_index(op.f("ix_negotiations_id"), table_name="negotiations")
    op.drop_index(op.f("ix_negotiations_expires_at"), table_name="negotiations")
    op.drop_index(op.f("ix_negotiations_booking_id"), table_name="negotiations")
    op.drop_index("idx_negotiations_user_id", table_name="negotiations")
    op.drop_index("idx_negotiations_status", table_name="negotiations")
    op.drop_index("idx_negotiations_booking_id", table_name="negotiations")
    op.drop_table("negotiations")
    op.drop_index(op.f("ix_massage_sessions_id"), table_name="massage_sessions")
    op.drop_index(op.f("ix_massage_sessions_booking_id"), table_name="massage_sessions")
    op.drop_index("idx_massage_sessions_booking_id", table_name="massage_sessions")
    op.drop_table("massage_sessions")
    op.drop_index(op.f("ix_booking_slots_therapist_id"), table_name="booking_slots")
    op.drop_index(op.f("ix_booking_slots_slot_date"), table_name="booking_slots")
    op.drop_index(op.f("ix_booking_slots_id"), table_name="booking_slots")
    op.drop_index("idx_booking_slots_therapist_id", table_name="booking_slots")
    op.drop_index("idx_booking_slots_slot_date", table_name="booking_slots")
    op.drop_index("idx_booking_slots_is_booked", table_name="booking_slots")
    op.drop_index("idx_booking_slots_is_available", table_name="booking_slots")
    op.drop_table("booking_slots")
    op.drop_index(op.f("ix_booking_analytics_id"), table_name="booking_analytics")
    op.drop_index(
        op.f("ix_booking_analytics_booking_id"), table_name="booking_analytics"
    )
    op.drop_table("booking_analytics")
    op.drop_index(op.f("ix_booking_addons_id"), table_name="booking_addons")
    op.drop_table("booking_addons")
    op.drop_index(op.f("ix_ai_predictions_user_id"), table_name="ai_predictions")
    op.drop_index(
        op.f("ix_ai_predictions_prediction_type"), table_name="ai_predictions"
    )
    op.drop_index(op.f("ix_ai_predictions_id"), table_name="ai_predictions")
    op.drop_index(op.f("ix_ai_predictions_booking_id"), table_name="ai_predictions")
    op.drop_index("idx_ai_predictions_user_id", table_name="ai_predictions")
    op.drop_index("idx_ai_predictions_prediction_type", table_name="ai_predictions")
    op.drop_index("idx_ai_predictions_created_at", table_name="ai_predictions")
    op.drop_index("idx_ai_predictions_booking_id", table_name="ai_predictions")
    op.drop_table("ai_predictions")
    op.drop_index(op.f("ix_withdrawals_therapist_id"), table_name="withdrawals")
    op.drop_index(op.f("ix_withdrawals_id"), table_name="withdrawals")
    op.drop_index("idx_withdrawals_therapist_id", table_name="withdrawals")
    op.drop_index("idx_withdrawals_status", table_name="withdrawals")
    op.drop_table("withdrawals")
    op.drop_index(op.f("ix_user_analytics_user_id"), table_name="user_analytics")
    op.drop_index(op.f("ix_user_analytics_id"), table_name="user_analytics")
    op.drop_index("idx_user_analytics_user_segment", table_name="user_analytics")
    op.drop_index("idx_user_analytics_user_id", table_name="user_analytics")
    op.drop_table("user_analytics")
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    op.drop_index("idx_transactions_user_id", table_name="transactions")
    op.drop_index("idx_transactions_type", table_name="transactions")
    op.drop_index("idx_transactions_created_at", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(
        op.f("ix_therapist_specialties_therapist_id"),
        table_name="therapist_specialties",
    )
    op.drop_index(
        op.f("ix_therapist_specialties_massage_type_id"),
        table_name="therapist_specialties",
    )
    op.drop_index(
        op.f("ix_therapist_specialties_id"), table_name="therapist_specialties"
    )
    op.drop_index(
        "idx_therapist_specialties_therapist_id", table_name="therapist_specialties"
    )
    op.drop_index(
        "idx_therapist_specialties_massage_type_id", table_name="therapist_specialties"
    )
    op.drop_table("therapist_specialties")
    op.drop_index(
        op.f("ix_therapist_ratings_therapist_id"), table_name="therapist_ratings"
    )
    op.drop_index(op.f("ix_therapist_ratings_id"), table_name="therapist_ratings")
    op.drop_table("therapist_ratings")
    op.drop_index(
        op.f("ix_therapist_earnings_therapist_id"), table_name="therapist_earnings"
    )
    op.drop_index(op.f("ix_therapist_earnings_id"), table_name="therapist_earnings")
    op.drop_table("therapist_earnings")
    op.drop_index(
        op.f("ix_therapist_availability_therapist_id"),
        table_name="therapist_availability",
    )
    op.drop_index(
        op.f("ix_therapist_availability_id"), table_name="therapist_availability"
    )
    op.drop_index(
        "idx_therapist_availability_therapist_id", table_name="therapist_availability"
    )
    op.drop_index(
        "idx_therapist_availability_day_of_week", table_name="therapist_availability"
    )
    op.drop_table("therapist_availability")
    op.drop_index(
        op.f("ix_notification_preferences_user_id"),
        table_name="notification_preferences",
    )
    op.drop_index(
        op.f("ix_notification_preferences_id"), table_name="notification_preferences"
    )
    op.drop_index(
        "idx_notification_preferences_user_id", table_name="notification_preferences"
    )
    op.drop_table("notification_preferences")
    op.drop_index(
        op.f("ix_emergency_contacts_user_id"), table_name="emergency_contacts"
    )
    op.drop_index(op.f("ix_emergency_contacts_id"), table_name="emergency_contacts")
    op.drop_index("idx_emergency_contacts_user_id", table_name="emergency_contacts")
    op.drop_table("emergency_contacts")
    op.drop_index(op.f("ix_bookings_therapist_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_status"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_scheduled_date"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_expires_at"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_created_at"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_client_id"), table_name="bookings")
    op.drop_index("idx_bookings_therapist_id", table_name="bookings")
    op.drop_index("idx_bookings_status", table_name="bookings")
    op.drop_index("idx_bookings_scheduled_date", table_name="bookings")
    op.drop_index("idx_bookings_expires_at", table_name="bookings")
    op.drop_index("idx_bookings_client_id", table_name="bookings")
    op.drop_table("bookings")
    op.drop_index(op.f("ix_blocked_dates_therapist_id"), table_name="blocked_dates")
    op.drop_index(op.f("ix_blocked_dates_start_date"), table_name="blocked_dates")
    op.drop_index(op.f("ix_blocked_dates_id"), table_name="blocked_dates")
    op.drop_index(op.f("ix_blocked_dates_end_date"), table_name="blocked_dates")
    op.drop_index("idx_blocked_dates_therapist_id", table_name="blocked_dates")
    op.drop_index("idx_blocked_dates_start_date", table_name="blocked_dates")
    op.drop_index("idx_blocked_dates_end_date", table_name="blocked_dates")
    op.drop_table("blocked_dates")
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index("idx_users_verification_status", table_name="users")
    op.drop_index("idx_users_role", table_name="users")
    op.drop_index("idx_users_phone", table_name="users")
    op.drop_index("idx_users_is_active", table_name="users")
    op.drop_index("idx_users_email", table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_platform_analytics_id"), table_name="platform_analytics")
    op.drop_index(op.f("ix_platform_analytics_date"), table_name="platform_analytics")
    op.drop_table("platform_analytics")
    op.drop_index(op.f("ix_massage_types_id"), table_name="massage_types")
    op.drop_table("massage_types")
    op.drop_index(op.f("ix_massage_categories_id"), table_name="massage_categories")
    op.drop_table("massage_categories")
    op.drop_index(op.f("ix_massage_addons_id"), table_name="massage_addons")
    op.drop_table("massage_addons")
    op.drop_index(op.f("ix_ai_models_id"), table_name="ai_models")
    op.drop_index("idx_ai_models_model_type", table_name="ai_models")
    op.drop_index("idx_ai_models_is_active", table_name="ai_models")
    op.drop_table("ai_models")
    # ### end Alembic commands ###
