"""add cin_number to users

Revision ID: c1f5070e0bcb
Revises: e37310ce3aa6
Create Date: 2026-08-11 14:23:17.882235

"""

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision = "c1f5070e0bcb"
down_revision = "e37310ce3aa6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_certificate_number"), table_name="therapist_certificates")
    op.drop_index(op.f("idx_certificate_status"), table_name="therapist_certificates")
    op.drop_index(
        op.f("idx_certificate_therapist"), table_name="therapist_certificates"
    )
    op.drop_index(
        op.f("ix_therapist_certificates_certificate_number"),
        table_name="therapist_certificates",
    )
    op.drop_index(
        op.f("ix_therapist_certificates_id"), table_name="therapist_certificates"
    )
    op.drop_index(
        op.f("ix_therapist_certificates_therapist_id"),
        table_name="therapist_certificates",
    )
    op.drop_table("therapist_certificates")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "therapist_certificates",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("therapist_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "certificate_number",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "certificate_path",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "issued_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("valid", "revoked", name="certificate_status"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("verified_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["users.id"],
            name=op.f("therapist_certificates_therapist_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
            name=op.f("therapist_certificates_verified_by_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("therapist_certificates_pkey")),
    )
    op.create_index(
        op.f("ix_therapist_certificates_therapist_id"),
        "therapist_certificates",
        ["therapist_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_therapist_certificates_id"),
        "therapist_certificates",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_therapist_certificates_certificate_number"),
        "therapist_certificates",
        ["certificate_number"],
        unique=True,
    )
    op.create_index(
        op.f("idx_certificate_therapist"),
        "therapist_certificates",
        ["therapist_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_certificate_status"),
        "therapist_certificates",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("idx_certificate_number"),
        "therapist_certificates",
        ["certificate_number"],
        unique=False,
    )
    # ### end Alembic commands ###
