"""add therapist assigned at

Revision ID: 3edd1a848ed6
Revises: 3a1b713daa55
Create Date: 2026-09-14 00:33:08.611150

"""

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# Revision identifiers, used by Alembic.
revision = "3edd1a848ed6"
down_revision = "3a1b713daa55"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings", sa.Column("therapist_assigned_at", sa.TIMESTAMP(), nullable=True)
    )
    op.create_index(
        "idx_bookings_therapist_assigned_at",
        "bookings",
        ["therapist_assigned_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bookings_therapist_assigned_at"),
        "bookings",
        ["therapist_assigned_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bookings_therapist_assigned_at"), table_name="bookings")
    op.drop_index("idx_bookings_therapist_assigned_at", table_name="bookings")
    op.drop_column("bookings", "therapist_assigned_at")
    # ### end Alembic commands ###
