"""fix notification type and priority

Revision ID: 788558d13ada
Revises:
Create Date: 2026-09-10 10:06:51.976028

"""

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision = "788558d13ada"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_notification_preferences_user_id"),
        table_name="notification_preferences",
    )
    op.alter_column(
        "notifications",
        "type",
        existing_type=postgresql.ENUM(
            "booking",
            "offer",
            "payment",
            "review",
            "sos",
            "system",
            "promotion",
            "reminder",
            "chat",
            "therapist",
            name="notification_type",
        ),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "notifications", "is_read", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "notifications", "is_delivered", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "notifications", "is_sent", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "notifications",
        "priority",
        existing_type=postgresql.ENUM(
            "low", "normal", "high", "urgent", name="notification_priority"
        ),
        type_=sa.String(length=20),
        nullable=False,
    )
    op.alter_column(
        "notifications",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_notifications_created_at"), table_name="notifications")
    op.drop_index(op.f("idx_notifications_is_read"), table_name="notifications")
    op.drop_index(op.f("idx_notifications_user_id"), table_name="notifications")
    op.create_index(
        "idx_notifications_booking_id", "notifications", ["booking_id"], unique=False
    )
    op.create_index(
        "idx_notifications_user_created",
        "notifications",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_notifications_user_read_created",
        "notifications",
        ["user_id", "is_read", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_notifications_user_read_created", table_name="notifications")
    op.drop_index("idx_notifications_user_created", table_name="notifications")
    op.drop_index("idx_notifications_booking_id", table_name="notifications")
    op.create_index(
        op.f("idx_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_notifications_is_read"), "notifications", ["is_read"], unique=False
    )
    op.create_index(
        op.f("idx_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
    )
    op.alter_column(
        "notifications",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "notifications",
        "priority",
        existing_type=sa.String(length=20),
        type_=postgresql.ENUM(
            "low", "normal", "high", "urgent", name="notification_priority"
        ),
        nullable=True,
    )
    op.alter_column(
        "notifications", "is_sent", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "notifications", "is_delivered", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "notifications", "is_read", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "notifications",
        "type",
        existing_type=sa.String(length=50),
        type_=postgresql.ENUM(
            "booking",
            "offer",
            "payment",
            "review",
            "sos",
            "system",
            "promotion",
            "reminder",
            "chat",
            "therapist",
            name="notification_type",
        ),
        existing_nullable=False,
    )
    op.create_index(
        op.f("idx_notification_preferences_user_id"),
        "notification_preferences",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###
