"""add certificate_professionnel column to users

Revision ID: aacd882d4b45
Revises:
Create Date: 2026-08-23 11:46:42.778598

"""

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# Revision identifiers, used by Alembic.
revision = "aacd882d4b45"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("certificate_professionnel", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "certificate_professionnel")
    # ### end Alembic commands ###
